// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/pb/agg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Hello 是握手发起方在握手流（protocol /netacc/agg/1.0.0）上发出的第一个
// 控制消息，用于协商一条新聚合流的参数（规格书 §4.1）。
type Hello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agg_stream_id：发起方生成的 128bit 随机聚合流标识。
	// 后续所有数据路径的 PATH_ATTACH 凭此 ID 绑定到同一条聚合流。
	AggStreamId   []byte `protobuf:"bytes,1,opt,name=agg_stream_id,json=aggStreamId,proto3" json:"agg_stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_internal_pb_agg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_internal_pb_agg_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetAggStreamId() []byte {
	if x != nil {
		return x.AggStreamId
	}
	return nil
}

// HelloAck 是接收方对 Hello 的应答：回显 agg_stream_id 即表示接受。
// 应答发出后，握手流升格为该聚合流的第一条数据路径（分离+复用混合，
// 规格书 §4.1）。
type HelloAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggStreamId   []byte                 `protobuf:"bytes,1,opt,name=agg_stream_id,json=aggStreamId,proto3" json:"agg_stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_internal_pb_agg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_internal_pb_agg_proto_rawDescGZIP(), []int{1}
}

func (x *HelloAck) GetAggStreamId() []byte {
	if x != nil {
		return x.AggStreamId
	}
	return nil
}

var File_internal_pb_agg_proto protoreflect.FileDescriptor

const file_internal_pb_agg_proto_rawDesc = "" +
	"\n" +
	"\x15internal/pb/agg.proto\x12\tnetacc.v1\"+\n" +
	"\x05Hello\x12\"\n" +
	"\ragg_stream_id\x18\x01 \x01(\fR\vaggStreamId\".\n" +
	"\bHelloAck\x12\"\n" +
	"\ragg_stream_id\x18\x01 \x01(\fR\vaggStreamIdB+Z)github.com/yangjuncode/netacc/internal/pbb\x06proto3"

var (
	file_internal_pb_agg_proto_rawDescOnce sync.Once
	file_internal_pb_agg_proto_rawDescData []byte
)

func file_internal_pb_agg_proto_rawDescGZIP() []byte {
	file_internal_pb_agg_proto_rawDescOnce.Do(func() {
		file_internal_pb_agg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_agg_proto_rawDesc), len(file_internal_pb_agg_proto_rawDesc)))
	})
	return file_internal_pb_agg_proto_rawDescData
}

var file_internal_pb_agg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_pb_agg_proto_goTypes = []any{
	(*Hello)(nil),    // 0: netacc.v1.Hello
	(*HelloAck)(nil), // 1: netacc.v1.HelloAck
}
var file_internal_pb_agg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_pb_agg_proto_init() }
func file_internal_pb_agg_proto_init() {
	if File_internal_pb_agg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_agg_proto_rawDesc), len(file_internal_pb_agg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_agg_proto_goTypes,
		DependencyIndexes: file_internal_pb_agg_proto_depIdxs,
		MessageInfos:      file_internal_pb_agg_proto_msgTypes,
	}.Build()
	File_internal_pb_agg_proto = out.File
	file_internal_pb_agg_proto_goTypes = nil
	file_internal_pb_agg_proto_depIdxs = nil
}
