// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: internal/pb/agg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Hello 是握手发起方在握手流（protocol /netacc/agg/1.0.0）上发出的第一个
// 控制消息，用于协商一条新聚合流的参数（规格书 §4.1）。
type Hello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agg_stream_id：发起方生成的 128bit 随机聚合流标识。
	// 后续所有数据路径的 PATH_ATTACH 凭此 ID 绑定到同一条聚合流。
	AggStreamId   []byte `protobuf:"bytes,1,opt,name=agg_stream_id,json=aggStreamId,proto3" json:"agg_stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_internal_pb_agg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_internal_pb_agg_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetAggStreamId() []byte {
	if x != nil {
		return x.AggStreamId
	}
	return nil
}

// HelloAck 是接收方对 Hello 的应答：回显 agg_stream_id 即表示接受。
// 应答发出后，握手流升格为该聚合流的第一条数据路径（分离+复用混合，
// 规格书 §4.1）。
type HelloAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggStreamId   []byte                 `protobuf:"bytes,1,opt,name=agg_stream_id,json=aggStreamId,proto3" json:"agg_stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_internal_pb_agg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_internal_pb_agg_proto_rawDescGZIP(), []int{1}
}

func (x *HelloAck) GetAggStreamId() []byte {
	if x != nil {
		return x.AggStreamId
	}
	return nil
}

// PathAttach 是 PATH_ATTACH 帧（帧类型 3）的 protobuf 帧体。
//
// 它是路径绑定子流（protocol /netacc/path/1.0.0）上的第一帧：加路径方
// 在新子流上发出，凭 agg_stream_id 把该子流绑定到既有的聚合流
// （连接级认证 + ID 绑定，规格书 §4.2）。接收方校验通过后回发一帧
// 内容相同的 PATH_ATTACH 作为接受应答；agg_stream_id 不认识或
// path_id 非法时直接 reset 子流。
type PathAttach struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要绑定的聚合流标识（128bit）。
	AggStreamId []byte `protobuf:"bytes,1,opt,name=agg_stream_id,json=aggStreamId,proto3" json:"agg_stream_id,omitempty"`
	// 加路径方分配的路径标识：最低位区分发起侧（0=聚合流发起方，
	// 1=接收方），其余位为各侧单调递增计数——分侧命名空间保证
	// 双向对称加路径时 path_id 不冲突（规格书 §4.3）。
	PathId        uint64 `protobuf:"varint,2,opt,name=path_id,json=pathId,proto3" json:"path_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathAttach) Reset() {
	*x = PathAttach{}
	mi := &file_internal_pb_agg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathAttach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathAttach) ProtoMessage() {}

func (x *PathAttach) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathAttach.ProtoReflect.Descriptor instead.
func (*PathAttach) Descriptor() ([]byte, []int) {
	return file_internal_pb_agg_proto_rawDescGZIP(), []int{2}
}

func (x *PathAttach) GetAggStreamId() []byte {
	if x != nil {
		return x.AggStreamId
	}
	return nil
}

func (x *PathAttach) GetPathId() uint64 {
	if x != nil {
		return x.PathId
	}
	return 0
}

// PathDrop 是 PATH_DROP 帧（帧类型 4）的 protobuf 帧体：告知对端
// 摘除其对端视角下对应 path_id 的路径。尽力而为，无应答。
type PathDrop struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 待摘除路径的 path_id（即 PATH_ATTACH 时加路径方分配的标识）。
	PathId        uint64 `protobuf:"varint,1,opt,name=path_id,json=pathId,proto3" json:"path_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathDrop) Reset() {
	*x = PathDrop{}
	mi := &file_internal_pb_agg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathDrop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathDrop) ProtoMessage() {}

func (x *PathDrop) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathDrop.ProtoReflect.Descriptor instead.
func (*PathDrop) Descriptor() ([]byte, []int) {
	return file_internal_pb_agg_proto_rawDescGZIP(), []int{3}
}

func (x *PathDrop) GetPathId() uint64 {
	if x != nil {
		return x.PathId
	}
	return 0
}

// PathRequest 是 PATH_REQUEST 帧（帧类型 5）的 protobuf 帧体：
// 加路径方在任意存活路径上发出，请求对端配合建立一条经中继的路径
// （中继路径的按需协调，规格书 §4.3）。帧体即中继路径描述符——
// 中继 peerID + 中继可达地址集 + 逐跳传输偏好。
//
// 逐跳偏好语义：A→C 段（发起方→中继）由 ac_addr 表达——发起方从
// 地址集挑定、随后体现到 CONNECT 的电路地址里，随帧告知对端便于
// 观测/调试；C→B 段即对端 reservation 所用传输，由对端自选，
// 不进帧体。
type PathRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id：发起方在聚合流内单调递增的序号，
	// 把随后的 PATH_READY 应答关联回本请求。
	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// 中继节点 peerID（原始字节）。
	RelayPeer []byte `protobuf:"bytes,2,opt,name=relay_peer,json=relayPeer,proto3" json:"relay_peer,omitempty"`
	// 中继可达地址集（multiaddr 字节，允许带 /p2p/<relay> 后缀，
	// 接收方剥离）。对端用它们连到中继做 reservation；空集时对端
	// 只能依赖 peerstore 已有信息。
	RelayAddrs [][]byte `protobuf:"bytes,3,rep,name=relay_addrs,json=relayAddrs,proto3" json:"relay_addrs,omitempty"`
	// A→C 段传输偏好：发起方选定的中继地址（multiaddr 字节，
	// 即随后电路地址内嵌的那条）。信息性字段——对端可忽略。
	AcAddr        []byte `protobuf:"bytes,4,opt,name=ac_addr,json=acAddr,proto3" json:"ac_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathRequest) Reset() {
	*x = PathRequest{}
	mi := &file_internal_pb_agg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathRequest) ProtoMessage() {}

func (x *PathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathRequest.ProtoReflect.Descriptor instead.
func (*PathRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_agg_proto_rawDescGZIP(), []int{4}
}

func (x *PathRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *PathRequest) GetRelayPeer() []byte {
	if x != nil {
		return x.RelayPeer
	}
	return nil
}

func (x *PathRequest) GetRelayAddrs() [][]byte {
	if x != nil {
		return x.RelayAddrs
	}
	return nil
}

func (x *PathRequest) GetAcAddr() []byte {
	if x != nil {
		return x.AcAddr
	}
	return nil
}

// PathReady 是 PATH_READY 帧（帧类型 6）的 protobuf 帧体：
// 对端完成（或失败）向中继的 reservation 后回送。error 为空表示成功，
// 发起方随后经 <relay-addr>/p2p/<relay>/p2p-circuit/p2p/<对端>
// 电路地址拨 CONNECT 建中继路径。
type PathReady struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 回显对应 PATH_REQUEST 的 request_id。
	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// 非空 = 对端 reservation 失败原因（错误透传给发起方）。
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathReady) Reset() {
	*x = PathReady{}
	mi := &file_internal_pb_agg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathReady) ProtoMessage() {}

func (x *PathReady) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathReady.ProtoReflect.Descriptor instead.
func (*PathReady) Descriptor() ([]byte, []int) {
	return file_internal_pb_agg_proto_rawDescGZIP(), []int{5}
}

func (x *PathReady) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *PathReady) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Ping 是 PING 帧（帧类型 7）的 protobuf 帧体：逐路径主动探测
// （规格书 §5.2：仅用于冷启动、est_rate 过期、疑似降级，不常态化）。
//
// 发起方置 reply=false 携带 send_ts；接收方在同一条路径上原样回显
// send_ts 并置 reply=true——应答固定走同路径返回，使测得的往返时延
// 天然归属该路径（区别于 ACK 回显的「正向路径+回程最快路径」混合样本，
// PING 样本是干净的单路径双向 RTT）。
type Ping struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 发送时间戳：微秒，与 DATA 帧 send_ts 同一基准（相对建流时刻）。
	SendTs uint64 `protobuf:"varint,1,opt,name=send_ts,json=sendTs,proto3" json:"send_ts,omitempty"`
	// false=探测请求；true=对探测的应答回显。
	Reply         bool `protobuf:"varint,2,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_internal_pb_agg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_internal_pb_agg_proto_rawDescGZIP(), []int{6}
}

func (x *Ping) GetSendTs() uint64 {
	if x != nil {
		return x.SendTs
	}
	return 0
}

func (x *Ping) GetReply() bool {
	if x != nil {
		return x.Reply
	}
	return false
}

// Telemetry 是 TELEMETRY 帧（帧类型 8）的 protobuf 帧体：收端周期
// 回报其观测到的各路径到达速率，供发送端校准 est_rate
// （规格书 §5.2：对端视角的到达速率比发端 ACK 自测更准）。
type Telemetry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 逐路径观测项；只包含有新到达字节的路径。
	Rates         []*PathRate `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_internal_pb_agg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_internal_pb_agg_proto_rawDescGZIP(), []int{7}
}

func (x *Telemetry) GetRates() []*PathRate {
	if x != nil {
		return x.Rates
	}
	return nil
}

// PathRate 是一条路径的收端观测速率。
type PathRate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 路径标识：PATH_ATTACH 时分配的 path_id，两端视图一致。
	PathId uint64 `protobuf:"varint,1,opt,name=path_id,json=pathId,proto3" json:"path_id,omitempty"`
	// 收端在上个回报周期内观测到的该路径到达速率（字节/秒）。
	RateBps       uint64 `protobuf:"varint,2,opt,name=rate_bps,json=rateBps,proto3" json:"rate_bps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathRate) Reset() {
	*x = PathRate{}
	mi := &file_internal_pb_agg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathRate) ProtoMessage() {}

func (x *PathRate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_agg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathRate.ProtoReflect.Descriptor instead.
func (*PathRate) Descriptor() ([]byte, []int) {
	return file_internal_pb_agg_proto_rawDescGZIP(), []int{8}
}

func (x *PathRate) GetPathId() uint64 {
	if x != nil {
		return x.PathId
	}
	return 0
}

func (x *PathRate) GetRateBps() uint64 {
	if x != nil {
		return x.RateBps
	}
	return 0
}

var File_internal_pb_agg_proto protoreflect.FileDescriptor

const file_internal_pb_agg_proto_rawDesc = "" +
	"\n" +
	"\x15internal/pb/agg.proto\x12\tnetacc.v1\"+\n" +
	"\x05Hello\x12\"\n" +
	"\ragg_stream_id\x18\x01 \x01(\fR\vaggStreamId\".\n" +
	"\bHelloAck\x12\"\n" +
	"\ragg_stream_id\x18\x01 \x01(\fR\vaggStreamId\"I\n" +
	"\n" +
	"PathAttach\x12\"\n" +
	"\ragg_stream_id\x18\x01 \x01(\fR\vaggStreamId\x12\x17\n" +
	"\apath_id\x18\x02 \x01(\x04R\x06pathId\"#\n" +
	"\bPathDrop\x12\x17\n" +
	"\apath_id\x18\x01 \x01(\x04R\x06pathId\"\x85\x01\n" +
	"\vPathRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1d\n" +
	"\n" +
	"relay_peer\x18\x02 \x01(\fR\trelayPeer\x12\x1f\n" +
	"\vrelay_addrs\x18\x03 \x03(\fR\n" +
	"relayAddrs\x12\x17\n" +
	"\aac_addr\x18\x04 \x01(\fR\x06acAddr\"@\n" +
	"\tPathReady\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"5\n" +
	"\x04Ping\x12\x17\n" +
	"\asend_ts\x18\x01 \x01(\x04R\x06sendTs\x12\x14\n" +
	"\x05reply\x18\x02 \x01(\bR\x05reply\"6\n" +
	"\tTelemetry\x12)\n" +
	"\x05rates\x18\x01 \x03(\v2\x13.netacc.v1.PathRateR\x05rates\">\n" +
	"\bPathRate\x12\x17\n" +
	"\apath_id\x18\x01 \x01(\x04R\x06pathId\x12\x19\n" +
	"\brate_bps\x18\x02 \x01(\x04R\arateBpsB+Z)github.com/yangjuncode/netacc/internal/pbb\x06proto3"

var (
	file_internal_pb_agg_proto_rawDescOnce sync.Once
	file_internal_pb_agg_proto_rawDescData []byte
)

func file_internal_pb_agg_proto_rawDescGZIP() []byte {
	file_internal_pb_agg_proto_rawDescOnce.Do(func() {
		file_internal_pb_agg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_agg_proto_rawDesc), len(file_internal_pb_agg_proto_rawDesc)))
	})
	return file_internal_pb_agg_proto_rawDescData
}

var file_internal_pb_agg_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_pb_agg_proto_goTypes = []any{
	(*Hello)(nil),       // 0: netacc.v1.Hello
	(*HelloAck)(nil),    // 1: netacc.v1.HelloAck
	(*PathAttach)(nil),  // 2: netacc.v1.PathAttach
	(*PathDrop)(nil),    // 3: netacc.v1.PathDrop
	(*PathRequest)(nil), // 4: netacc.v1.PathRequest
	(*PathReady)(nil),   // 5: netacc.v1.PathReady
	(*Ping)(nil),        // 6: netacc.v1.Ping
	(*Telemetry)(nil),   // 7: netacc.v1.Telemetry
	(*PathRate)(nil),    // 8: netacc.v1.PathRate
}
var file_internal_pb_agg_proto_depIdxs = []int32{
	8, // 0: netacc.v1.Telemetry.rates:type_name -> netacc.v1.PathRate
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_pb_agg_proto_init() }
func file_internal_pb_agg_proto_init() {
	if File_internal_pb_agg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_agg_proto_rawDesc), len(file_internal_pb_agg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_agg_proto_goTypes,
		DependencyIndexes: file_internal_pb_agg_proto_depIdxs,
		MessageInfos:      file_internal_pb_agg_proto_msgTypes,
	}.Build()
	File_internal_pb_agg_proto = out.File
	file_internal_pb_agg_proto_goTypes = nil
	file_internal_pb_agg_proto_depIdxs = nil
}
